language: "node_js"

node_js:
  - "10.11.0"

install:
  - npm install -g bids-validator@1.3.9

script:
  # Validating the BIDS datasets using bids-validator
  # and then checking for large files (there shouldn't be any)
  - |
    rc=0;
    for i in $(ls -d */);
    do
      echo "Validating dataset" $i
      bids-validator ${i%%/} --ignoreNiftiHeaders -c bidsconfig.json || rc=$?
    done

    echo "Checking for big files ..."
    found=`find . -not -path "./.git*" -type f -size +500k`
    if [ "$found" == "" ]
    then
      echo "No big files present, great!"
      exit $rc;
    else
      echo "Found big files:"
      echo "$found"
      exit 1;
    fi
