node_js:
  - "8.0.0"

install:
  - npm install -g https://github.com/bids-standard/bids-validator.git

script:
  - |
    rc=0;
    for i in $(ls -d */);
    do
      echo "Validating dataset" $i
      bids-validator ${i%%/} --bep006 --ignoreNiftiHeaders -c bidsconfig.json || rc=$?
    done
    exit $rc;
